
check-mypy:
	@echo "no op - swh-docs does not need typechecking, skipping"

all:
	@echo Building the whole documentation from source code repositories
	@echo available in ../ via tox. This can take a while.
	@echo Please be patient.
	tox -vv -r -e sphinx-dev

pip-install-swh-dev:
	python3 -m pip install pifpaf
	sed 's/#.*$$//;/^$$/d' requirements-swh-dev.txt | \
	while IFS= read -r package; do \
	  python3 -m pip install $$package ; \
	done
